# fly.toml file for voice-ai-agent
app = "voice-ai-agent"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3000"
  LIVEKIT_URL = "ws://localhost:7880"
  LIVEKIT_API_KEY = "devkey"
  LIVEKIT_API_SECRET = "secret"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.tls_options]
    alpn = ["http/1.1"]
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# LiveKit WebSocket service
[[services]]
  internal_port = 7880
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = "4433"
    handlers = ["tls", "http"]
    tls_options = { alpn = ["http/1.1"] }

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

# LiveKit TCP service
[[services]]
  internal_port = 7881
  protocol = "tcp"
  processes = ["app"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024