# fly.toml app configuration file generated for liveagent on 2025-10-01T22:11:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liveagent'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
